name: Build and Deploy Raylib to Pages

on:
  push:
    branches: [main] # Деплоїмо тільки коли пушиш в main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build Raylib (Web)
        run: |
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_WEB -B
          cd ../..

      - name: Build Project
        run: |
          RAYLIB_PATH=$(pwd)/raylib/src
          em++ main.cpp -o index.html \
          $RAYLIB_PATH/libraylib.web.a \
          -I. -I$RAYLIB_PATH \
          -L. -L$RAYLIB_PATH \
          -s USE_GLFW=3 \
          -s ASYNCIFY \
          -DPLATFORM_WEB \
          --shell-file $RAYLIB_PATH/shell.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Завантажуємо корінь, де лежать index.html, .js та .wasm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
