name: Build Raylib for Web

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Download and Build Raylib (Web)
        run: |
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_WEB -B
          # Ось він, наш підступний файл:
          ls -l libraylib.web.a 
          cd ../..

      - name: Build Project
        run: |
          RAYLIB_PATH=$(pwd)/raylib/src
          
          # Тут теж міняємо на .web.a
          em++ -o index.html main.cpp $RAYLIB_PATH/libraylib.web.a \
          -I. -I$RAYLIB_PATH \
          -L. -L$RAYLIB_PATH \
          -s USE_GLFW=3 \
          -s ASYNCIFY \
          -DPLATFORM_WEB \
          --shell-file $RAYLIB_PATH/shell.html \
          --preload-file assets || echo "Папки assets нема, але ігноримо це"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: |
            index.html
            index.js
            index.wasm
