name: Build Raylib for Web

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest

      - name: Build Raylib (Web)
        run: |
          git clone --depth 1 https://github.com/raysan5/raylib.git
          cd raylib/src
          make PLATFORM=PLATFORM_WEB -B
          cd ../..

      - name: Build Project
        run: |
          RAYLIB_PATH=$(pwd)/raylib/src
          
          # Я прибрала --preload-file, бо він валить збірку
          em++ main.cpp -o index.html \
          $RAYLIB_PATH/libraylib.web.a \
          -I. -I$RAYLIB_PATH \
          -L. -L$RAYLIB_PATH \
          -s USE_GLFW=3 \
          -s ASYNCIFY \
          -DPLATFORM_WEB \
          --shell-file $RAYLIB_PATH/shell.html

          echo "ПОШУК ФАЙЛІВ ПІСЛЯ ЗБІРКИ:"
          ls -F index.*
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: index*
